language: c
dist: xenial

branches:
  except:
    - docs
    
addons:
 apt:
   packages:
    - gfortran
    - openmpi-bin libopenmpi-dev
    - libblas-dev liblapack-dev
    - netcdf-bin libnetcdf-dev libnetcdff-dev


before_script:


script:
  - mkdir build; cd build; FC=gfortran cmake ../ -DLETKF_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DLETKF_ENABLE_CODECOVERAGE=ON -DLETKF_ENABLE_GRIB=ON -DLETKF_BUILD_GRIB=ON;
  - make
  - ctest -VV



after_success:
  bash <(curl -s https://codecov.io/bash)
